// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actor.proto

package org.cloudfoundry.iam.perm;

public interface ActorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cloud_foundry.perm.protos.Actor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 2 [(.gogoproto.customname) = "ID"];</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 2 [(.gogoproto.customname) = "ID"];</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string namespace = 3;</code>
   */
  java.lang.String getNamespace();
  /**
   * <code>string namespace = 3;</code>
   */
  com.google.protobuf.ByteString
      getNamespaceBytes();
}
