// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: role_service.proto

package org.cloudfoundry.iam.perm;

public interface CreateRoleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cloud_foundry.perm.protos.CreateRoleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated .cloud_foundry.perm.protos.Permission permissions = 2;</code>
   */
  java.util.List<Permission>
      getPermissionsList();
  /**
   * <code>repeated .cloud_foundry.perm.protos.Permission permissions = 2;</code>
   */
  Permission getPermissions(int index);
  /**
   * <code>repeated .cloud_foundry.perm.protos.Permission permissions = 2;</code>
   */
  int getPermissionsCount();
  /**
   * <code>repeated .cloud_foundry.perm.protos.Permission permissions = 2;</code>
   */
  java.util.List<? extends PermissionOrBuilder>
      getPermissionsOrBuilderList();
  /**
   * <code>repeated .cloud_foundry.perm.protos.Permission permissions = 2;</code>
   */
  PermissionOrBuilder getPermissionsOrBuilder(
      int index);
}
