// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: role_service.proto

package org.cloudfoundry.iam.perm;

public interface CreateRoleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cloud_foundry.perm.protos.CreateRoleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.cloud_foundry.perm.protos.Role role = 1;</code>
   */
  boolean hasRole();
  /**
   * <code>.cloud_foundry.perm.protos.Role role = 1;</code>
   */
  Role getRole();
  /**
   * <code>.cloud_foundry.perm.protos.Role role = 1;</code>
   */
  RoleOrBuilder getRoleOrBuilder();
}
