// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: role_service.proto

package org.cloudfoundry.iam.perm;

public interface DeleteRoleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cloud_foundry.perm.protos.DeleteRoleResponse)
    com.google.protobuf.MessageOrBuilder {
}
