// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: group.proto

package org.cloudfoundry.iam.perm;

public interface GroupOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cloud_foundry.perm.protos.Group)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 2 [(.gogoproto.customname) = "ID"];</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 2 [(.gogoproto.customname) = "ID"];</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
