// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: permission_service.proto

package org.cloudfoundry.iam.perm;

public interface HasPermissionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cloud_foundry.perm.protos.HasPermissionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool has_permission = 1;</code>
   */
  boolean getHasPermission();
}
