// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: role_service.proto

package org.cloudfoundry.iam.perm;

public interface HasRoleForGroupRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cloud_foundry.perm.protos.HasRoleForGroupRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.cloud_foundry.perm.protos.Group group = 1;</code>
   */
  boolean hasGroup();
  /**
   * <code>.cloud_foundry.perm.protos.Group group = 1;</code>
   */
  Group getGroup();
  /**
   * <code>.cloud_foundry.perm.protos.Group group = 1;</code>
   */
  GroupOrBuilder getGroupOrBuilder();

  /**
   * <code>string role_name = 2;</code>
   */
  java.lang.String getRoleName();
  /**
   * <code>string role_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getRoleNameBytes();
}
