// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: role_service.proto

package org.cloudfoundry.iam.perm;

public interface HasRoleForGroupResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cloud_foundry.perm.protos.HasRoleForGroupResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool has_role = 1;</code>
   */
  boolean getHasRole();
}
