// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: role_service.proto

package org.cloudfoundry.iam.perm;

public interface HasRoleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cloud_foundry.perm.protos.HasRoleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.cloud_foundry.perm.protos.Actor actor = 1;</code>
   */
  boolean hasActor();
  /**
   * <code>.cloud_foundry.perm.protos.Actor actor = 1;</code>
   */
  Actor getActor();
  /**
   * <code>.cloud_foundry.perm.protos.Actor actor = 1;</code>
   */
  ActorOrBuilder getActorOrBuilder();

  /**
   * <code>string role_name = 2;</code>
   */
  java.lang.String getRoleName();
  /**
   * <code>string role_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getRoleNameBytes();
}
