// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: permission_service.proto

package org.cloudfoundry.iam.perm;

public interface ListResourcePatternsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cloud_foundry.perm.protos.ListResourcePatternsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string resource_patterns = 2;</code>
   */
  java.util.List<java.lang.String>
      getResourcePatternsList();
  /**
   * <code>repeated string resource_patterns = 2;</code>
   */
  int getResourcePatternsCount();
  /**
   * <code>repeated string resource_patterns = 2;</code>
   */
  java.lang.String getResourcePatterns(int index);
  /**
   * <code>repeated string resource_patterns = 2;</code>
   */
  com.google.protobuf.ByteString
      getResourcePatternsBytes(int index);
}
