// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: permission_service.proto

package org.cloudfoundry.iam.perm;

/**
 * Protobuf type {@code cloud_foundry.perm.protos.ListResourcePatternsRequest}
 */
public  final class ListResourcePatternsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cloud_foundry.perm.protos.ListResourcePatternsRequest)
    ListResourcePatternsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListResourcePatternsRequest.newBuilder() to construct.
  private ListResourcePatternsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListResourcePatternsRequest() {
    action_ = "";
    groups_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListResourcePatternsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 18: {
            Actor.Builder subBuilder = null;
            if (actor_ != null) {
              subBuilder = actor_.toBuilder();
            }
            actor_ = input.readMessage(Actor.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(actor_);
              actor_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            action_ = s;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              groups_ = new java.util.ArrayList<Group>();
              mutable_bitField0_ |= 0x00000004;
            }
            groups_.add(
                input.readMessage(Group.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        groups_ = java.util.Collections.unmodifiableList(groups_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return PermissionServiceOuterClass.internal_static_cloud_foundry_perm_protos_ListResourcePatternsRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return PermissionServiceOuterClass.internal_static_cloud_foundry_perm_protos_ListResourcePatternsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ListResourcePatternsRequest.class, ListResourcePatternsRequest.Builder.class);
  }

  private int bitField0_;
  public static final int ACTOR_FIELD_NUMBER = 2;
  private Actor actor_;
  /**
   * <code>.cloud_foundry.perm.protos.Actor actor = 2;</code>
   */
  public boolean hasActor() {
    return actor_ != null;
  }
  /**
   * <code>.cloud_foundry.perm.protos.Actor actor = 2;</code>
   */
  public Actor getActor() {
    return actor_ == null ? Actor.getDefaultInstance() : actor_;
  }
  /**
   * <code>.cloud_foundry.perm.protos.Actor actor = 2;</code>
   */
  public ActorOrBuilder getActorOrBuilder() {
    return getActor();
  }

  public static final int ACTION_FIELD_NUMBER = 3;
  private volatile java.lang.Object action_;
  /**
   * <code>string action = 3;</code>
   */
  public java.lang.String getAction() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      action_ = s;
      return s;
    }
  }
  /**
   * <code>string action = 3;</code>
   */
  public com.google.protobuf.ByteString
      getActionBytes() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      action_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GROUPS_FIELD_NUMBER = 4;
  private java.util.List<Group> groups_;
  /**
   * <code>repeated .cloud_foundry.perm.protos.Group groups = 4;</code>
   */
  public java.util.List<Group> getGroupsList() {
    return groups_;
  }
  /**
   * <code>repeated .cloud_foundry.perm.protos.Group groups = 4;</code>
   */
  public java.util.List<? extends GroupOrBuilder>
      getGroupsOrBuilderList() {
    return groups_;
  }
  /**
   * <code>repeated .cloud_foundry.perm.protos.Group groups = 4;</code>
   */
  public int getGroupsCount() {
    return groups_.size();
  }
  /**
   * <code>repeated .cloud_foundry.perm.protos.Group groups = 4;</code>
   */
  public Group getGroups(int index) {
    return groups_.get(index);
  }
  /**
   * <code>repeated .cloud_foundry.perm.protos.Group groups = 4;</code>
   */
  public GroupOrBuilder getGroupsOrBuilder(
      int index) {
    return groups_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (actor_ != null) {
      output.writeMessage(2, getActor());
    }
    if (!getActionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, action_);
    }
    for (int i = 0; i < groups_.size(); i++) {
      output.writeMessage(4, groups_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (actor_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getActor());
    }
    if (!getActionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, action_);
    }
    for (int i = 0; i < groups_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, groups_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ListResourcePatternsRequest)) {
      return super.equals(obj);
    }
    ListResourcePatternsRequest other = (ListResourcePatternsRequest) obj;

    boolean result = true;
    result = result && (hasActor() == other.hasActor());
    if (hasActor()) {
      result = result && getActor()
          .equals(other.getActor());
    }
    result = result && getAction()
        .equals(other.getAction());
    result = result && getGroupsList()
        .equals(other.getGroupsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasActor()) {
      hash = (37 * hash) + ACTOR_FIELD_NUMBER;
      hash = (53 * hash) + getActor().hashCode();
    }
    hash = (37 * hash) + ACTION_FIELD_NUMBER;
    hash = (53 * hash) + getAction().hashCode();
    if (getGroupsCount() > 0) {
      hash = (37 * hash) + GROUPS_FIELD_NUMBER;
      hash = (53 * hash) + getGroupsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ListResourcePatternsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ListResourcePatternsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ListResourcePatternsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ListResourcePatternsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ListResourcePatternsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ListResourcePatternsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ListResourcePatternsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ListResourcePatternsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ListResourcePatternsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ListResourcePatternsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ListResourcePatternsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ListResourcePatternsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ListResourcePatternsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cloud_foundry.perm.protos.ListResourcePatternsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cloud_foundry.perm.protos.ListResourcePatternsRequest)
      ListResourcePatternsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PermissionServiceOuterClass.internal_static_cloud_foundry_perm_protos_ListResourcePatternsRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PermissionServiceOuterClass.internal_static_cloud_foundry_perm_protos_ListResourcePatternsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ListResourcePatternsRequest.class, ListResourcePatternsRequest.Builder.class);
    }

    // Construct using ListResourcePatternsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getGroupsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (actorBuilder_ == null) {
        actor_ = null;
      } else {
        actor_ = null;
        actorBuilder_ = null;
      }
      action_ = "";

      if (groupsBuilder_ == null) {
        groups_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        groupsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return PermissionServiceOuterClass.internal_static_cloud_foundry_perm_protos_ListResourcePatternsRequest_descriptor;
    }

    public ListResourcePatternsRequest getDefaultInstanceForType() {
      return ListResourcePatternsRequest.getDefaultInstance();
    }

    public ListResourcePatternsRequest build() {
      ListResourcePatternsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ListResourcePatternsRequest buildPartial() {
      ListResourcePatternsRequest result = new ListResourcePatternsRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (actorBuilder_ == null) {
        result.actor_ = actor_;
      } else {
        result.actor_ = actorBuilder_.build();
      }
      result.action_ = action_;
      if (groupsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          groups_ = java.util.Collections.unmodifiableList(groups_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.groups_ = groups_;
      } else {
        result.groups_ = groupsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ListResourcePatternsRequest) {
        return mergeFrom((ListResourcePatternsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ListResourcePatternsRequest other) {
      if (other == ListResourcePatternsRequest.getDefaultInstance()) return this;
      if (other.hasActor()) {
        mergeActor(other.getActor());
      }
      if (!other.getAction().isEmpty()) {
        action_ = other.action_;
        onChanged();
      }
      if (groupsBuilder_ == null) {
        if (!other.groups_.isEmpty()) {
          if (groups_.isEmpty()) {
            groups_ = other.groups_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureGroupsIsMutable();
            groups_.addAll(other.groups_);
          }
          onChanged();
        }
      } else {
        if (!other.groups_.isEmpty()) {
          if (groupsBuilder_.isEmpty()) {
            groupsBuilder_.dispose();
            groupsBuilder_ = null;
            groups_ = other.groups_;
            bitField0_ = (bitField0_ & ~0x00000004);
            groupsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getGroupsFieldBuilder() : null;
          } else {
            groupsBuilder_.addAllMessages(other.groups_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ListResourcePatternsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ListResourcePatternsRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Actor actor_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        Actor, Actor.Builder, ActorOrBuilder> actorBuilder_;
    /**
     * <code>.cloud_foundry.perm.protos.Actor actor = 2;</code>
     */
    public boolean hasActor() {
      return actorBuilder_ != null || actor_ != null;
    }
    /**
     * <code>.cloud_foundry.perm.protos.Actor actor = 2;</code>
     */
    public Actor getActor() {
      if (actorBuilder_ == null) {
        return actor_ == null ? Actor.getDefaultInstance() : actor_;
      } else {
        return actorBuilder_.getMessage();
      }
    }
    /**
     * <code>.cloud_foundry.perm.protos.Actor actor = 2;</code>
     */
    public Builder setActor(Actor value) {
      if (actorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        actor_ = value;
        onChanged();
      } else {
        actorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.cloud_foundry.perm.protos.Actor actor = 2;</code>
     */
    public Builder setActor(
        Actor.Builder builderForValue) {
      if (actorBuilder_ == null) {
        actor_ = builderForValue.build();
        onChanged();
      } else {
        actorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.cloud_foundry.perm.protos.Actor actor = 2;</code>
     */
    public Builder mergeActor(Actor value) {
      if (actorBuilder_ == null) {
        if (actor_ != null) {
          actor_ =
            Actor.newBuilder(actor_).mergeFrom(value).buildPartial();
        } else {
          actor_ = value;
        }
        onChanged();
      } else {
        actorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.cloud_foundry.perm.protos.Actor actor = 2;</code>
     */
    public Builder clearActor() {
      if (actorBuilder_ == null) {
        actor_ = null;
        onChanged();
      } else {
        actor_ = null;
        actorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.cloud_foundry.perm.protos.Actor actor = 2;</code>
     */
    public Actor.Builder getActorBuilder() {
      
      onChanged();
      return getActorFieldBuilder().getBuilder();
    }
    /**
     * <code>.cloud_foundry.perm.protos.Actor actor = 2;</code>
     */
    public ActorOrBuilder getActorOrBuilder() {
      if (actorBuilder_ != null) {
        return actorBuilder_.getMessageOrBuilder();
      } else {
        return actor_ == null ?
            Actor.getDefaultInstance() : actor_;
      }
    }
    /**
     * <code>.cloud_foundry.perm.protos.Actor actor = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Actor, Actor.Builder, ActorOrBuilder>
        getActorFieldBuilder() {
      if (actorBuilder_ == null) {
        actorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Actor, Actor.Builder, ActorOrBuilder>(
                getActor(),
                getParentForChildren(),
                isClean());
        actor_ = null;
      }
      return actorBuilder_;
    }

    private java.lang.Object action_ = "";
    /**
     * <code>string action = 3;</code>
     */
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        action_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string action = 3;</code>
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string action = 3;</code>
     */
    public Builder setAction(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      action_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string action = 3;</code>
     */
    public Builder clearAction() {
      
      action_ = getDefaultInstance().getAction();
      onChanged();
      return this;
    }
    /**
     * <code>string action = 3;</code>
     */
    public Builder setActionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      action_ = value;
      onChanged();
      return this;
    }

    private java.util.List<Group> groups_ =
      java.util.Collections.emptyList();
    private void ensureGroupsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        groups_ = new java.util.ArrayList<Group>(groups_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        Group, Group.Builder, GroupOrBuilder> groupsBuilder_;

    /**
     * <code>repeated .cloud_foundry.perm.protos.Group groups = 4;</code>
     */
    public java.util.List<Group> getGroupsList() {
      if (groupsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(groups_);
      } else {
        return groupsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .cloud_foundry.perm.protos.Group groups = 4;</code>
     */
    public int getGroupsCount() {
      if (groupsBuilder_ == null) {
        return groups_.size();
      } else {
        return groupsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .cloud_foundry.perm.protos.Group groups = 4;</code>
     */
    public Group getGroups(int index) {
      if (groupsBuilder_ == null) {
        return groups_.get(index);
      } else {
        return groupsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .cloud_foundry.perm.protos.Group groups = 4;</code>
     */
    public Builder setGroups(
        int index, Group value) {
      if (groupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupsIsMutable();
        groups_.set(index, value);
        onChanged();
      } else {
        groupsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .cloud_foundry.perm.protos.Group groups = 4;</code>
     */
    public Builder setGroups(
        int index, Group.Builder builderForValue) {
      if (groupsBuilder_ == null) {
        ensureGroupsIsMutable();
        groups_.set(index, builderForValue.build());
        onChanged();
      } else {
        groupsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cloud_foundry.perm.protos.Group groups = 4;</code>
     */
    public Builder addGroups(Group value) {
      if (groupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupsIsMutable();
        groups_.add(value);
        onChanged();
      } else {
        groupsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .cloud_foundry.perm.protos.Group groups = 4;</code>
     */
    public Builder addGroups(
        int index, Group value) {
      if (groupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupsIsMutable();
        groups_.add(index, value);
        onChanged();
      } else {
        groupsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .cloud_foundry.perm.protos.Group groups = 4;</code>
     */
    public Builder addGroups(
        Group.Builder builderForValue) {
      if (groupsBuilder_ == null) {
        ensureGroupsIsMutable();
        groups_.add(builderForValue.build());
        onChanged();
      } else {
        groupsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cloud_foundry.perm.protos.Group groups = 4;</code>
     */
    public Builder addGroups(
        int index, Group.Builder builderForValue) {
      if (groupsBuilder_ == null) {
        ensureGroupsIsMutable();
        groups_.add(index, builderForValue.build());
        onChanged();
      } else {
        groupsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cloud_foundry.perm.protos.Group groups = 4;</code>
     */
    public Builder addAllGroups(
        java.lang.Iterable<? extends Group> values) {
      if (groupsBuilder_ == null) {
        ensureGroupsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, groups_);
        onChanged();
      } else {
        groupsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .cloud_foundry.perm.protos.Group groups = 4;</code>
     */
    public Builder clearGroups() {
      if (groupsBuilder_ == null) {
        groups_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        groupsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .cloud_foundry.perm.protos.Group groups = 4;</code>
     */
    public Builder removeGroups(int index) {
      if (groupsBuilder_ == null) {
        ensureGroupsIsMutable();
        groups_.remove(index);
        onChanged();
      } else {
        groupsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .cloud_foundry.perm.protos.Group groups = 4;</code>
     */
    public Group.Builder getGroupsBuilder(
        int index) {
      return getGroupsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .cloud_foundry.perm.protos.Group groups = 4;</code>
     */
    public GroupOrBuilder getGroupsOrBuilder(
        int index) {
      if (groupsBuilder_ == null) {
        return groups_.get(index);  } else {
        return groupsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .cloud_foundry.perm.protos.Group groups = 4;</code>
     */
    public java.util.List<? extends GroupOrBuilder>
         getGroupsOrBuilderList() {
      if (groupsBuilder_ != null) {
        return groupsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(groups_);
      }
    }
    /**
     * <code>repeated .cloud_foundry.perm.protos.Group groups = 4;</code>
     */
    public Group.Builder addGroupsBuilder() {
      return getGroupsFieldBuilder().addBuilder(
          Group.getDefaultInstance());
    }
    /**
     * <code>repeated .cloud_foundry.perm.protos.Group groups = 4;</code>
     */
    public Group.Builder addGroupsBuilder(
        int index) {
      return getGroupsFieldBuilder().addBuilder(
          index, Group.getDefaultInstance());
    }
    /**
     * <code>repeated .cloud_foundry.perm.protos.Group groups = 4;</code>
     */
    public java.util.List<Group.Builder>
         getGroupsBuilderList() {
      return getGroupsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        Group, Group.Builder, GroupOrBuilder>
        getGroupsFieldBuilder() {
      if (groupsBuilder_ == null) {
        groupsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            Group, Group.Builder, GroupOrBuilder>(
                groups_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        groups_ = null;
      }
      return groupsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cloud_foundry.perm.protos.ListResourcePatternsRequest)
  }

  // @@protoc_insertion_point(class_scope:cloud_foundry.perm.protos.ListResourcePatternsRequest)
  private static final ListResourcePatternsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ListResourcePatternsRequest();
  }

  public static ListResourcePatternsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListResourcePatternsRequest>
      PARSER = new com.google.protobuf.AbstractParser<ListResourcePatternsRequest>() {
    public ListResourcePatternsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListResourcePatternsRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListResourcePatternsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListResourcePatternsRequest> getParserForType() {
    return PARSER;
  }

  public ListResourcePatternsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

