// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: permission_service.proto

package org.cloudfoundry.iam.perm;

/**
 * Protobuf type {@code cloud_foundry.perm.protos.ListResourcePatternsResponse}
 */
public  final class ListResourcePatternsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cloud_foundry.perm.protos.ListResourcePatternsResponse)
    ListResourcePatternsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListResourcePatternsResponse.newBuilder() to construct.
  private ListResourcePatternsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListResourcePatternsResponse() {
    resourcePatterns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListResourcePatternsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              resourcePatterns_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            resourcePatterns_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        resourcePatterns_ = resourcePatterns_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return PermissionServiceOuterClass.internal_static_cloud_foundry_perm_protos_ListResourcePatternsResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return PermissionServiceOuterClass.internal_static_cloud_foundry_perm_protos_ListResourcePatternsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ListResourcePatternsResponse.class, ListResourcePatternsResponse.Builder.class);
  }

  public static final int RESOURCE_PATTERNS_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList resourcePatterns_;
  /**
   * <code>repeated string resource_patterns = 2;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getResourcePatternsList() {
    return resourcePatterns_;
  }
  /**
   * <code>repeated string resource_patterns = 2;</code>
   */
  public int getResourcePatternsCount() {
    return resourcePatterns_.size();
  }
  /**
   * <code>repeated string resource_patterns = 2;</code>
   */
  public java.lang.String getResourcePatterns(int index) {
    return resourcePatterns_.get(index);
  }
  /**
   * <code>repeated string resource_patterns = 2;</code>
   */
  public com.google.protobuf.ByteString
      getResourcePatternsBytes(int index) {
    return resourcePatterns_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < resourcePatterns_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, resourcePatterns_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < resourcePatterns_.size(); i++) {
        dataSize += computeStringSizeNoTag(resourcePatterns_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getResourcePatternsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ListResourcePatternsResponse)) {
      return super.equals(obj);
    }
    ListResourcePatternsResponse other = (ListResourcePatternsResponse) obj;

    boolean result = true;
    result = result && getResourcePatternsList()
        .equals(other.getResourcePatternsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getResourcePatternsCount() > 0) {
      hash = (37 * hash) + RESOURCE_PATTERNS_FIELD_NUMBER;
      hash = (53 * hash) + getResourcePatternsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ListResourcePatternsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ListResourcePatternsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ListResourcePatternsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ListResourcePatternsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ListResourcePatternsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ListResourcePatternsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ListResourcePatternsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ListResourcePatternsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ListResourcePatternsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ListResourcePatternsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ListResourcePatternsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ListResourcePatternsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ListResourcePatternsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cloud_foundry.perm.protos.ListResourcePatternsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cloud_foundry.perm.protos.ListResourcePatternsResponse)
      ListResourcePatternsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PermissionServiceOuterClass.internal_static_cloud_foundry_perm_protos_ListResourcePatternsResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PermissionServiceOuterClass.internal_static_cloud_foundry_perm_protos_ListResourcePatternsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ListResourcePatternsResponse.class, ListResourcePatternsResponse.Builder.class);
    }

    // Construct using ListResourcePatternsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      resourcePatterns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return PermissionServiceOuterClass.internal_static_cloud_foundry_perm_protos_ListResourcePatternsResponse_descriptor;
    }

    public ListResourcePatternsResponse getDefaultInstanceForType() {
      return ListResourcePatternsResponse.getDefaultInstance();
    }

    public ListResourcePatternsResponse build() {
      ListResourcePatternsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ListResourcePatternsResponse buildPartial() {
      ListResourcePatternsResponse result = new ListResourcePatternsResponse(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        resourcePatterns_ = resourcePatterns_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.resourcePatterns_ = resourcePatterns_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ListResourcePatternsResponse) {
        return mergeFrom((ListResourcePatternsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ListResourcePatternsResponse other) {
      if (other == ListResourcePatternsResponse.getDefaultInstance()) return this;
      if (!other.resourcePatterns_.isEmpty()) {
        if (resourcePatterns_.isEmpty()) {
          resourcePatterns_ = other.resourcePatterns_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureResourcePatternsIsMutable();
          resourcePatterns_.addAll(other.resourcePatterns_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ListResourcePatternsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ListResourcePatternsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList resourcePatterns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureResourcePatternsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        resourcePatterns_ = new com.google.protobuf.LazyStringArrayList(resourcePatterns_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string resource_patterns = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getResourcePatternsList() {
      return resourcePatterns_.getUnmodifiableView();
    }
    /**
     * <code>repeated string resource_patterns = 2;</code>
     */
    public int getResourcePatternsCount() {
      return resourcePatterns_.size();
    }
    /**
     * <code>repeated string resource_patterns = 2;</code>
     */
    public java.lang.String getResourcePatterns(int index) {
      return resourcePatterns_.get(index);
    }
    /**
     * <code>repeated string resource_patterns = 2;</code>
     */
    public com.google.protobuf.ByteString
        getResourcePatternsBytes(int index) {
      return resourcePatterns_.getByteString(index);
    }
    /**
     * <code>repeated string resource_patterns = 2;</code>
     */
    public Builder setResourcePatterns(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureResourcePatternsIsMutable();
      resourcePatterns_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string resource_patterns = 2;</code>
     */
    public Builder addResourcePatterns(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureResourcePatternsIsMutable();
      resourcePatterns_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string resource_patterns = 2;</code>
     */
    public Builder addAllResourcePatterns(
        java.lang.Iterable<java.lang.String> values) {
      ensureResourcePatternsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, resourcePatterns_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string resource_patterns = 2;</code>
     */
    public Builder clearResourcePatterns() {
      resourcePatterns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string resource_patterns = 2;</code>
     */
    public Builder addResourcePatternsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureResourcePatternsIsMutable();
      resourcePatterns_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cloud_foundry.perm.protos.ListResourcePatternsResponse)
  }

  // @@protoc_insertion_point(class_scope:cloud_foundry.perm.protos.ListResourcePatternsResponse)
  private static final ListResourcePatternsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ListResourcePatternsResponse();
  }

  public static ListResourcePatternsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListResourcePatternsResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListResourcePatternsResponse>() {
    public ListResourcePatternsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListResourcePatternsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListResourcePatternsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListResourcePatternsResponse> getParserForType() {
    return PARSER;
  }

  public ListResourcePatternsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

