// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: role_service.proto

package org.cloudfoundry.iam.perm;

public interface ListRolePermissionsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cloud_foundry.perm.protos.ListRolePermissionsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string role_name = 2;</code>
   */
  java.lang.String getRoleName();
  /**
   * <code>string role_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getRoleNameBytes();
}
