// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: permission_service.proto

package org.cloudfoundry.iam.perm;

public final class PermissionServiceOuterClass {
  private PermissionServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_foundry_perm_protos_HasPermissionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cloud_foundry_perm_protos_HasPermissionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_foundry_perm_protos_HasPermissionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cloud_foundry_perm_protos_HasPermissionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_foundry_perm_protos_ListResourcePatternsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cloud_foundry_perm_protos_ListResourcePatternsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_foundry_perm_protos_ListResourcePatternsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cloud_foundry_perm_protos_ListResourcePatternsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030permission_service.proto\022\031cloud_foundr" +
      "y.perm.protos\032-github.com/gogo/protobuf/" +
      "gogoproto/gogo.proto\032\013actor.proto\032\013group" +
      ".proto\"\233\001\n\024HasPermissionRequest\022/\n\005actor" +
      "\030\001 \001(\0132 .cloud_foundry.perm.protos.Actor" +
      "\022\016\n\006action\030\002 \001(\t\022\020\n\010resource\030\003 \001(\t\0220\n\006gr" +
      "oups\030\004 \003(\0132 .cloud_foundry.perm.protos.G" +
      "roup\"/\n\025HasPermissionResponse\022\026\n\016has_per" +
      "mission\030\001 \001(\010\"\226\001\n\033ListResourcePatternsRe" +
      "quest\022/\n\005actor\030\002 \001(\0132 .cloud_foundry.per" +
      "m.protos.Actor\022\016\n\006action\030\003 \001(\t\0220\n\006groups" +
      "\030\004 \003(\0132 .cloud_foundry.perm.protos.Group" +
      "J\004\010\001\020\002\"?\n\034ListResourcePatternsResponse\022\031" +
      "\n\021resource_patterns\030\002 \003(\tJ\004\010\001\020\0022\221\002\n\021Perm" +
      "issionService\022r\n\rHasPermission\022/.cloud_f" +
      "oundry.perm.protos.HasPermissionRequest\032" +
      "0.cloud_foundry.perm.protos.HasPermissio" +
      "nResponse\022\207\001\n\024ListResourcePatterns\0226.clo" +
      "ud_foundry.perm.protos.ListResourcePatte" +
      "rnsRequest\0327.cloud_foundry.perm.protos.L" +
      "istResourcePatternsResponseB1\n\031org.cloud" +
      "foundry.iam.permP\001Z\006protos\310\342\036\001\340\342\036\001\320\342\036\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
          ActorOuterClass.getDescriptor(),
          GroupOuterClass.getDescriptor(),
        }, assigner);
    internal_static_cloud_foundry_perm_protos_HasPermissionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cloud_foundry_perm_protos_HasPermissionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cloud_foundry_perm_protos_HasPermissionRequest_descriptor,
        new java.lang.String[] { "Actor", "Action", "Resource", "Groups", });
    internal_static_cloud_foundry_perm_protos_HasPermissionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cloud_foundry_perm_protos_HasPermissionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cloud_foundry_perm_protos_HasPermissionResponse_descriptor,
        new java.lang.String[] { "HasPermission", });
    internal_static_cloud_foundry_perm_protos_ListResourcePatternsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cloud_foundry_perm_protos_ListResourcePatternsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cloud_foundry_perm_protos_ListResourcePatternsRequest_descriptor,
        new java.lang.String[] { "Actor", "Action", "Groups", });
    internal_static_cloud_foundry_perm_protos_ListResourcePatternsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_cloud_foundry_perm_protos_ListResourcePatternsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cloud_foundry_perm_protos_ListResourcePatternsResponse_descriptor,
        new java.lang.String[] { "ResourcePatterns", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.marshalerAll);
    registry.add(com.google.protobuf.GoGoProtos.sizerAll);
    registry.add(com.google.protobuf.GoGoProtos.unmarshalerAll);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
    ActorOuterClass.getDescriptor();
    GroupOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
