// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: permission.proto

package org.cloudfoundry.iam.perm;

public interface PermissionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cloud_foundry.perm.protos.Permission)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string action = 2;</code>
   */
  java.lang.String getAction();
  /**
   * <code>string action = 2;</code>
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <code>string resource_pattern = 3;</code>
   */
  java.lang.String getResourcePattern();
  /**
   * <code>string resource_pattern = 3;</code>
   */
  com.google.protobuf.ByteString
      getResourcePatternBytes();
}
