// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: role.proto

package org.cloudfoundry.iam.perm;

public interface RoleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cloud_foundry.perm.protos.Role)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
