// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: role_service.proto

package org.cloudfoundry.iam.perm;

public final class RoleServiceOuterClass {
  private RoleServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_foundry_perm_protos_CreateRoleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cloud_foundry_perm_protos_CreateRoleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_foundry_perm_protos_CreateRoleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cloud_foundry_perm_protos_CreateRoleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_foundry_perm_protos_DeleteRoleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cloud_foundry_perm_protos_DeleteRoleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_foundry_perm_protos_DeleteRoleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cloud_foundry_perm_protos_DeleteRoleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_foundry_perm_protos_AssignRoleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cloud_foundry_perm_protos_AssignRoleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_foundry_perm_protos_AssignRoleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cloud_foundry_perm_protos_AssignRoleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_foundry_perm_protos_AssignRoleToGroupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cloud_foundry_perm_protos_AssignRoleToGroupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_foundry_perm_protos_AssignRoleToGroupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cloud_foundry_perm_protos_AssignRoleToGroupResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_foundry_perm_protos_UnassignRoleFromGroupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cloud_foundry_perm_protos_UnassignRoleFromGroupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_foundry_perm_protos_UnassignRoleFromGroupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cloud_foundry_perm_protos_UnassignRoleFromGroupResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_foundry_perm_protos_UnassignRoleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cloud_foundry_perm_protos_UnassignRoleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_foundry_perm_protos_UnassignRoleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cloud_foundry_perm_protos_UnassignRoleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_foundry_perm_protos_HasRoleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cloud_foundry_perm_protos_HasRoleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_foundry_perm_protos_HasRoleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cloud_foundry_perm_protos_HasRoleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_foundry_perm_protos_HasRoleForGroupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cloud_foundry_perm_protos_HasRoleForGroupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_foundry_perm_protos_HasRoleForGroupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cloud_foundry_perm_protos_HasRoleForGroupResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_foundry_perm_protos_ListRolePermissionsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cloud_foundry_perm_protos_ListRolePermissionsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_foundry_perm_protos_ListRolePermissionsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cloud_foundry_perm_protos_ListRolePermissionsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022role_service.proto\022\031cloud_foundry.perm" +
      ".protos\032-github.com/gogo/protobuf/gogopr" +
      "oto/gogo.proto\032\013actor.proto\032\013group.proto" +
      "\032\020permission.proto\032\nrole.proto\"]\n\021Create" +
      "RoleRequest\022\014\n\004name\030\001 \001(\t\022:\n\013permissions" +
      "\030\002 \003(\0132%.cloud_foundry.perm.protos.Permi" +
      "ssion\"C\n\022CreateRoleResponse\022-\n\004role\030\001 \001(" +
      "\0132\037.cloud_foundry.perm.protos.Role\"!\n\021De" +
      "leteRoleRequest\022\014\n\004name\030\001 \001(\t\"\024\n\022DeleteR" +
      "oleResponse\"W\n\021AssignRoleRequest\022/\n\005acto" +
      "r\030\001 \001(\0132 .cloud_foundry.perm.protos.Acto" +
      "r\022\021\n\trole_name\030\002 \001(\t\"\024\n\022AssignRoleRespon" +
      "se\"^\n\030AssignRoleToGroupRequest\022/\n\005group\030" +
      "\001 \001(\0132 .cloud_foundry.perm.protos.Group\022" +
      "\021\n\trole_name\030\002 \001(\t\"\033\n\031AssignRoleToGroupR" +
      "esponse\"b\n\034UnassignRoleFromGroupRequest\022" +
      "/\n\005group\030\001 \001(\0132 .cloud_foundry.perm.prot" +
      "os.Group\022\021\n\trole_name\030\002 \001(\t\"\037\n\035UnassignR" +
      "oleFromGroupResponse\"Y\n\023UnassignRoleRequ" +
      "est\022/\n\005actor\030\001 \001(\0132 .cloud_foundry.perm." +
      "protos.Actor\022\021\n\trole_name\030\002 \001(\t\"\026\n\024Unass" +
      "ignRoleResponse\"T\n\016HasRoleRequest\022/\n\005act" +
      "or\030\001 \001(\0132 .cloud_foundry.perm.protos.Act" +
      "or\022\021\n\trole_name\030\002 \001(\t\"#\n\017HasRoleResponse" +
      "\022\020\n\010has_role\030\001 \001(\010\"\\\n\026HasRoleForGroupReq" +
      "uest\022/\n\005group\030\001 \001(\0132 .cloud_foundry.perm" +
      ".protos.Group\022\021\n\trole_name\030\002 \001(\t\"+\n\027HasR" +
      "oleForGroupResponse\022\020\n\010has_role\030\001 \001(\010\"5\n" +
      "\032ListRolePermissionsRequest\022\021\n\trole_name" +
      "\030\002 \001(\tJ\004\010\001\020\002\"_\n\033ListRolePermissionsRespo" +
      "nse\022:\n\013permissions\030\002 \003(\0132%.cloud_foundry" +
      ".perm.protos.PermissionJ\004\010\001\020\0022\257\010\n\013RoleSe" +
      "rvice\022i\n\nCreateRole\022,.cloud_foundry.perm" +
      ".protos.CreateRoleRequest\032-.cloud_foundr" +
      "y.perm.protos.CreateRoleResponse\022i\n\nDele" +
      "teRole\022,.cloud_foundry.perm.protos.Delet" +
      "eRoleRequest\032-.cloud_foundry.perm.protos" +
      ".DeleteRoleResponse\022i\n\nAssignRole\022,.clou" +
      "d_foundry.perm.protos.AssignRoleRequest\032" +
      "-.cloud_foundry.perm.protos.AssignRoleRe" +
      "sponse\022~\n\021AssignRoleToGroup\0223.cloud_foun" +
      "dry.perm.protos.AssignRoleToGroupRequest" +
      "\0324.cloud_foundry.perm.protos.AssignRoleT" +
      "oGroupResponse\022o\n\014UnassignRole\022..cloud_f" +
      "oundry.perm.protos.UnassignRoleRequest\032/" +
      ".cloud_foundry.perm.protos.UnassignRoleR" +
      "esponse\022\212\001\n\025UnassignRoleFromGroup\0227.clou" +
      "d_foundry.perm.protos.UnassignRoleFromGr" +
      "oupRequest\0328.cloud_foundry.perm.protos.U" +
      "nassignRoleFromGroupResponse\022`\n\007HasRole\022" +
      ").cloud_foundry.perm.protos.HasRoleReque" +
      "st\032*.cloud_foundry.perm.protos.HasRoleRe" +
      "sponse\022x\n\017HasRoleForGroup\0221.cloud_foundr" +
      "y.perm.protos.HasRoleForGroupRequest\0322.c" +
      "loud_foundry.perm.protos.HasRoleForGroup" +
      "Response\022\204\001\n\023ListRolePermissions\0225.cloud" +
      "_foundry.perm.protos.ListRolePermissions" +
      "Request\0326.cloud_foundry.perm.protos.List" +
      "RolePermissionsResponseB1\n\031org.cloudfoun" +
      "dry.iam.permP\001Z\006protos\310\342\036\001\340\342\036\001\320\342\036\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
          ActorOuterClass.getDescriptor(),
          GroupOuterClass.getDescriptor(),
          PermissionOuterClass.getDescriptor(),
          RoleOuterClass.getDescriptor(),
        }, assigner);
    internal_static_cloud_foundry_perm_protos_CreateRoleRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cloud_foundry_perm_protos_CreateRoleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cloud_foundry_perm_protos_CreateRoleRequest_descriptor,
        new java.lang.String[] { "Name", "Permissions", });
    internal_static_cloud_foundry_perm_protos_CreateRoleResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cloud_foundry_perm_protos_CreateRoleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cloud_foundry_perm_protos_CreateRoleResponse_descriptor,
        new java.lang.String[] { "Role", });
    internal_static_cloud_foundry_perm_protos_DeleteRoleRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cloud_foundry_perm_protos_DeleteRoleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cloud_foundry_perm_protos_DeleteRoleRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_cloud_foundry_perm_protos_DeleteRoleResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_cloud_foundry_perm_protos_DeleteRoleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cloud_foundry_perm_protos_DeleteRoleResponse_descriptor,
        new java.lang.String[] { });
    internal_static_cloud_foundry_perm_protos_AssignRoleRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_cloud_foundry_perm_protos_AssignRoleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cloud_foundry_perm_protos_AssignRoleRequest_descriptor,
        new java.lang.String[] { "Actor", "RoleName", });
    internal_static_cloud_foundry_perm_protos_AssignRoleResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_cloud_foundry_perm_protos_AssignRoleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cloud_foundry_perm_protos_AssignRoleResponse_descriptor,
        new java.lang.String[] { });
    internal_static_cloud_foundry_perm_protos_AssignRoleToGroupRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_cloud_foundry_perm_protos_AssignRoleToGroupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cloud_foundry_perm_protos_AssignRoleToGroupRequest_descriptor,
        new java.lang.String[] { "Group", "RoleName", });
    internal_static_cloud_foundry_perm_protos_AssignRoleToGroupResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_cloud_foundry_perm_protos_AssignRoleToGroupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cloud_foundry_perm_protos_AssignRoleToGroupResponse_descriptor,
        new java.lang.String[] { });
    internal_static_cloud_foundry_perm_protos_UnassignRoleFromGroupRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_cloud_foundry_perm_protos_UnassignRoleFromGroupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cloud_foundry_perm_protos_UnassignRoleFromGroupRequest_descriptor,
        new java.lang.String[] { "Group", "RoleName", });
    internal_static_cloud_foundry_perm_protos_UnassignRoleFromGroupResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_cloud_foundry_perm_protos_UnassignRoleFromGroupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cloud_foundry_perm_protos_UnassignRoleFromGroupResponse_descriptor,
        new java.lang.String[] { });
    internal_static_cloud_foundry_perm_protos_UnassignRoleRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_cloud_foundry_perm_protos_UnassignRoleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cloud_foundry_perm_protos_UnassignRoleRequest_descriptor,
        new java.lang.String[] { "Actor", "RoleName", });
    internal_static_cloud_foundry_perm_protos_UnassignRoleResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_cloud_foundry_perm_protos_UnassignRoleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cloud_foundry_perm_protos_UnassignRoleResponse_descriptor,
        new java.lang.String[] { });
    internal_static_cloud_foundry_perm_protos_HasRoleRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_cloud_foundry_perm_protos_HasRoleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cloud_foundry_perm_protos_HasRoleRequest_descriptor,
        new java.lang.String[] { "Actor", "RoleName", });
    internal_static_cloud_foundry_perm_protos_HasRoleResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_cloud_foundry_perm_protos_HasRoleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cloud_foundry_perm_protos_HasRoleResponse_descriptor,
        new java.lang.String[] { "HasRole", });
    internal_static_cloud_foundry_perm_protos_HasRoleForGroupRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_cloud_foundry_perm_protos_HasRoleForGroupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cloud_foundry_perm_protos_HasRoleForGroupRequest_descriptor,
        new java.lang.String[] { "Group", "RoleName", });
    internal_static_cloud_foundry_perm_protos_HasRoleForGroupResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_cloud_foundry_perm_protos_HasRoleForGroupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cloud_foundry_perm_protos_HasRoleForGroupResponse_descriptor,
        new java.lang.String[] { "HasRole", });
    internal_static_cloud_foundry_perm_protos_ListRolePermissionsRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_cloud_foundry_perm_protos_ListRolePermissionsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cloud_foundry_perm_protos_ListRolePermissionsRequest_descriptor,
        new java.lang.String[] { "RoleName", });
    internal_static_cloud_foundry_perm_protos_ListRolePermissionsResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_cloud_foundry_perm_protos_ListRolePermissionsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cloud_foundry_perm_protos_ListRolePermissionsResponse_descriptor,
        new java.lang.String[] { "Permissions", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.marshalerAll);
    registry.add(com.google.protobuf.GoGoProtos.sizerAll);
    registry.add(com.google.protobuf.GoGoProtos.unmarshalerAll);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
    ActorOuterClass.getDescriptor();
    GroupOuterClass.getDescriptor();
    PermissionOuterClass.getDescriptor();
    RoleOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
