// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: role_service.proto

package org.cloudfoundry.iam.perm;

/**
 * Protobuf type {@code cloud_foundry.perm.protos.UnassignRoleRequest}
 */
public  final class UnassignRoleRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cloud_foundry.perm.protos.UnassignRoleRequest)
    UnassignRoleRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UnassignRoleRequest.newBuilder() to construct.
  private UnassignRoleRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UnassignRoleRequest() {
    roleName_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UnassignRoleRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            Actor.Builder subBuilder = null;
            if (actor_ != null) {
              subBuilder = actor_.toBuilder();
            }
            actor_ = input.readMessage(Actor.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(actor_);
              actor_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            roleName_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return RoleServiceOuterClass.internal_static_cloud_foundry_perm_protos_UnassignRoleRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return RoleServiceOuterClass.internal_static_cloud_foundry_perm_protos_UnassignRoleRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            UnassignRoleRequest.class, UnassignRoleRequest.Builder.class);
  }

  public static final int ACTOR_FIELD_NUMBER = 1;
  private Actor actor_;
  /**
   * <code>.cloud_foundry.perm.protos.Actor actor = 1;</code>
   */
  public boolean hasActor() {
    return actor_ != null;
  }
  /**
   * <code>.cloud_foundry.perm.protos.Actor actor = 1;</code>
   */
  public Actor getActor() {
    return actor_ == null ? Actor.getDefaultInstance() : actor_;
  }
  /**
   * <code>.cloud_foundry.perm.protos.Actor actor = 1;</code>
   */
  public ActorOrBuilder getActorOrBuilder() {
    return getActor();
  }

  public static final int ROLE_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object roleName_;
  /**
   * <code>string role_name = 2;</code>
   */
  public java.lang.String getRoleName() {
    java.lang.Object ref = roleName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      roleName_ = s;
      return s;
    }
  }
  /**
   * <code>string role_name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getRoleNameBytes() {
    java.lang.Object ref = roleName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      roleName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (actor_ != null) {
      output.writeMessage(1, getActor());
    }
    if (!getRoleNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, roleName_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (actor_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getActor());
    }
    if (!getRoleNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, roleName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof UnassignRoleRequest)) {
      return super.equals(obj);
    }
    UnassignRoleRequest other = (UnassignRoleRequest) obj;

    boolean result = true;
    result = result && (hasActor() == other.hasActor());
    if (hasActor()) {
      result = result && getActor()
          .equals(other.getActor());
    }
    result = result && getRoleName()
        .equals(other.getRoleName());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasActor()) {
      hash = (37 * hash) + ACTOR_FIELD_NUMBER;
      hash = (53 * hash) + getActor().hashCode();
    }
    hash = (37 * hash) + ROLE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getRoleName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static UnassignRoleRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UnassignRoleRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UnassignRoleRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UnassignRoleRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UnassignRoleRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UnassignRoleRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UnassignRoleRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static UnassignRoleRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static UnassignRoleRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static UnassignRoleRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static UnassignRoleRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static UnassignRoleRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(UnassignRoleRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cloud_foundry.perm.protos.UnassignRoleRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cloud_foundry.perm.protos.UnassignRoleRequest)
      UnassignRoleRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RoleServiceOuterClass.internal_static_cloud_foundry_perm_protos_UnassignRoleRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RoleServiceOuterClass.internal_static_cloud_foundry_perm_protos_UnassignRoleRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UnassignRoleRequest.class, UnassignRoleRequest.Builder.class);
    }

    // Construct using UnassignRoleRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (actorBuilder_ == null) {
        actor_ = null;
      } else {
        actor_ = null;
        actorBuilder_ = null;
      }
      roleName_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return RoleServiceOuterClass.internal_static_cloud_foundry_perm_protos_UnassignRoleRequest_descriptor;
    }

    public UnassignRoleRequest getDefaultInstanceForType() {
      return UnassignRoleRequest.getDefaultInstance();
    }

    public UnassignRoleRequest build() {
      UnassignRoleRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public UnassignRoleRequest buildPartial() {
      UnassignRoleRequest result = new UnassignRoleRequest(this);
      if (actorBuilder_ == null) {
        result.actor_ = actor_;
      } else {
        result.actor_ = actorBuilder_.build();
      }
      result.roleName_ = roleName_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof UnassignRoleRequest) {
        return mergeFrom((UnassignRoleRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(UnassignRoleRequest other) {
      if (other == UnassignRoleRequest.getDefaultInstance()) return this;
      if (other.hasActor()) {
        mergeActor(other.getActor());
      }
      if (!other.getRoleName().isEmpty()) {
        roleName_ = other.roleName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      UnassignRoleRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (UnassignRoleRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Actor actor_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        Actor, Actor.Builder, ActorOrBuilder> actorBuilder_;
    /**
     * <code>.cloud_foundry.perm.protos.Actor actor = 1;</code>
     */
    public boolean hasActor() {
      return actorBuilder_ != null || actor_ != null;
    }
    /**
     * <code>.cloud_foundry.perm.protos.Actor actor = 1;</code>
     */
    public Actor getActor() {
      if (actorBuilder_ == null) {
        return actor_ == null ? Actor.getDefaultInstance() : actor_;
      } else {
        return actorBuilder_.getMessage();
      }
    }
    /**
     * <code>.cloud_foundry.perm.protos.Actor actor = 1;</code>
     */
    public Builder setActor(Actor value) {
      if (actorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        actor_ = value;
        onChanged();
      } else {
        actorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.cloud_foundry.perm.protos.Actor actor = 1;</code>
     */
    public Builder setActor(
        Actor.Builder builderForValue) {
      if (actorBuilder_ == null) {
        actor_ = builderForValue.build();
        onChanged();
      } else {
        actorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.cloud_foundry.perm.protos.Actor actor = 1;</code>
     */
    public Builder mergeActor(Actor value) {
      if (actorBuilder_ == null) {
        if (actor_ != null) {
          actor_ =
            Actor.newBuilder(actor_).mergeFrom(value).buildPartial();
        } else {
          actor_ = value;
        }
        onChanged();
      } else {
        actorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.cloud_foundry.perm.protos.Actor actor = 1;</code>
     */
    public Builder clearActor() {
      if (actorBuilder_ == null) {
        actor_ = null;
        onChanged();
      } else {
        actor_ = null;
        actorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.cloud_foundry.perm.protos.Actor actor = 1;</code>
     */
    public Actor.Builder getActorBuilder() {
      
      onChanged();
      return getActorFieldBuilder().getBuilder();
    }
    /**
     * <code>.cloud_foundry.perm.protos.Actor actor = 1;</code>
     */
    public ActorOrBuilder getActorOrBuilder() {
      if (actorBuilder_ != null) {
        return actorBuilder_.getMessageOrBuilder();
      } else {
        return actor_ == null ?
            Actor.getDefaultInstance() : actor_;
      }
    }
    /**
     * <code>.cloud_foundry.perm.protos.Actor actor = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Actor, Actor.Builder, ActorOrBuilder>
        getActorFieldBuilder() {
      if (actorBuilder_ == null) {
        actorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Actor, Actor.Builder, ActorOrBuilder>(
                getActor(),
                getParentForChildren(),
                isClean());
        actor_ = null;
      }
      return actorBuilder_;
    }

    private java.lang.Object roleName_ = "";
    /**
     * <code>string role_name = 2;</code>
     */
    public java.lang.String getRoleName() {
      java.lang.Object ref = roleName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roleName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string role_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRoleNameBytes() {
      java.lang.Object ref = roleName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roleName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string role_name = 2;</code>
     */
    public Builder setRoleName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      roleName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string role_name = 2;</code>
     */
    public Builder clearRoleName() {
      
      roleName_ = getDefaultInstance().getRoleName();
      onChanged();
      return this;
    }
    /**
     * <code>string role_name = 2;</code>
     */
    public Builder setRoleNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      roleName_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cloud_foundry.perm.protos.UnassignRoleRequest)
  }

  // @@protoc_insertion_point(class_scope:cloud_foundry.perm.protos.UnassignRoleRequest)
  private static final UnassignRoleRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new UnassignRoleRequest();
  }

  public static UnassignRoleRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UnassignRoleRequest>
      PARSER = new com.google.protobuf.AbstractParser<UnassignRoleRequest>() {
    public UnassignRoleRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UnassignRoleRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UnassignRoleRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UnassignRoleRequest> getParserForType() {
    return PARSER;
  }

  public UnassignRoleRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

